README.md
=> [Test] Branch Test

back/package.json, back/tsconfig.json
package.json에 module추가
typescript config 설정
=> [Add] module추가 및 tsconfig 설정

back/app.ts, back/src/models/task.model.ts, back/src/models/user.model.ts
=> [Add] backend model 정의

front/src/styles/InputBox.module.css, front/src/styles/common/color.css, front/src/styles/common/size.css
인풋박스 css 스타일링과 color,size 파일 내용 추가했습니다.
수정하고 싶은 사항이 있으면 코멘트 달아주세요!
https://user-images.githubusercontent.com/80464961/114724843-ef371b80-9d76-11eb-9aac-6a8578241ef2.mov
완성 동영상입니다.
=> [Add] 재사용컴포넌트 인풋박스 css 스타일링

front/src/App.jsx, front/src/components/Button.jsx, front/src/components/IconButton.jsx, front/src/styles/Button.module.css, front/src/styles/IconButton.module.css
- 간단한 props를 전달하여 재사용 할 수 있는 Button.jsx 컴포넌트 추가
- Button.module.css 추가
- 스타일링 및 테스트 위해 App.jsx에 버튼 컴포넌트 추가
외 2 커밋
=> [Add] 버튼 컴포넌트 추가 외 2

back/src/controllers/v1/account.controller.ts, back/src/middlewares/Google.ts, back/src/models/task.model.ts, back/src/routes/v1/account.route.ts, back/src/services/v1/account.service.ts
[Add] 기능별 작성자 추가
[Fix]  users.count => users.countDocuments로 변경
사유: Model.count 함수 deprecated됨
[Fix] authorization 변수들 => Authorization변경
=> [Add] 회원탈퇴기능 추가 외 3

.github/ISSUE_TEMPLATE/todo_template
=> Create issues todo_template

back/src/routes/index.ts, back/src/routes/v1/profile.route.ts, back/src/services/v1/profile.service.ts
=> [add] 프로필 조회 서비스.ts 코드 추가

front/src/styles/Button.module.css, front/src/styles/IconButton.module.css, front/src/styles/InputBox.module.css, front/src/styles/common/color.css, front/src/styles/common/size.css
버튼 컴포넌트 css 스타일링입니다.
버튼 radius를 2가지로 만들어보았는데요.
https://user-images.githubusercontent.com/80464961/114882157-a21e7c80-9e3e-11eb-9672-1279c5616e77.mov
https://user-images.githubusercontent.com/80464961/114882167-a3e84000-9e3e-11eb-997c-444d80226bf9.mov
현재 피그마 디자인과 가장 비슷한 네모에 가까운 형태로 지정했습니다.
그런데 버튼 ui 검색하다보니 요즘 둥근게 또 유행인 거 같더라구요.
살짝 곁들어보았는데 혹~~시 둥근게 더 괜찮으면 말해주세요! 
수정해야 할 사항 있으면 말씀해주세요~~~ 😸 
(그림자 자세히 봐주시면 감사하겠습니다.... 뭔가 애매해서....ㅠ)
=> [Add] 버튼 컴포넌트 css 스타일링

front/src/styles/Button.module.css, front/src/styles/InputBox.module.css, front/src/styles/common/effect.css, front/src/styles/common/size.css
자주 쓰이게 될 속성들을 common.css 파일에 추가, 정리하였습니다.
이에 따라 css 파일도 수정하였습니다.
혹시 common 파일에 더 추가할 내용이 있거나 삭제하고 싶으시다면 코멘트 달아주세요!
=> [Add] Css common 파일 추가 및 수정

front/src/App.jsx, front/src/components/Button.jsx, front/src/components/IconButton.jsx, front/src/components/InputBox.jsx, front/src/components/ProfileButon.jsx, front/src/components/ProfileImage.jsx, front/src/components/ProfileModal.jsx, front/src/container/Modal.jsx, front/src/container/Navbar.jsx, front/src/styles/Modal.module.css
- 프레임으로 쓰일 Modal 컴포넌트 추가
- 재사용 위해 프로필 이미지를 ProfileImage로 컴포넌트화
- ProfileButton 컴포넌트에 img 태그 -> ProfileImage로 변경
- 테스트 위해 App.jsx에 ProfileModal 컴포넌트 삽입
close #30
=> [Add] ProfileModal 컴포넌트 추가 #30

back/prettierrc.json, back/tsconfig.json
prettier 셋팅 프론트와 맞춤
tsconfig strictNullChecks 사용
close #48
=> [Chore] prettier 및 tsconfig수정 

front/.prettierrc.js, front/package.json, front/src/.eslintrc.json, front/yarn.lock
- Prettier 세팅 변경
- ESLint 세팅 변경
- .eslintrc.json 파일로 설정 분리
- eslint-plugin-prettier 패키지 설치
close #47
=> [Chore] Prettier, ESLint 설정 변경 #47

front/src/components/ProfileModal.jsx, front/src/styles/Button.module.css, front/src/styles/Modal.module.css, front/src/styles/ProfileImage.module.css, front/src/styles/ProfileModal.module.css, front/src/styles/common/color.css, front/src/styles/common/size.css
완성된 이미지입니다. (버튼은 살짝 무시해주세요 😅)
이게 디자인 시안인데 조금 더 진행된 후 손봐야 할 것 같습니다!
혹시 수정하고 싶은 부분있으면 말씀해주세요~~
close #35
=> [Add] 프로필 css 스타일링

front/.eslintrc.json, front/.prettierrc.js, front/src/.eslintrc.json, front/src/App.jsx, front/src/components/BrightStarIcon.jsx, front/src/components/Button.jsx, front/src/components/CheckButton.jsx, front/src/components/IconButton.jsx, front/src/components/InputBox.jsx, front/src/components/MenuSelector.jsx, front/src/components/PriorityIcon.jsx, front/src/components/ProfileButon.jsx, front/src/components/ProfileImage.jsx, front/src/components/TaskItem.jsx, front/src/components/TaskList.jsx, front/src/container/Modal.jsx, front/src/styles/BrightStarIcon.module.css, front/src/styles/Button.module.css, front/src/styles/CheckButton.module.css, front/src/styles/PriorityIcon.module.css, front/src/styles/TaskItem.module.css, front/src/utils/timestamp-parser.js
=> [Style] 코드 스타일 컨벤션 반영 외 2

back/src/controllers/v1/account.controller.ts, back/src/routes/v1/account.route.ts, back/src/services/v1/account.service.ts
=> [Add] 회원가입 여부 확인 API

front/src/App.jsx, front/src/styles/Button.module.css, front/src/styles/MenuSelector.module.css, front/src/styles/Navbar.module.css, front/src/styles/common/color.css
https://user-images.githubusercontent.com/80464961/116067189-e3771d80-a6c3-11eb-9fd1-61659ac21e30.mov
수정사항 있으면 말씀해주세요~~
(색깔은 이것저것 시도중이니 살짝 무시해주세요! 😄)
close #65
=> [Add] navbar css 스타일링

front/src/App.jsx, front/src/components/Calendar.jsx, front/src/components/QuickButton.jsx, front/src/components/useCalendar.jsx, front/yarn.lock
=> [Add] calendar 추가

front/src/components/BrightStarIcon.jsx, front/src/components/PriorityIcon.jsx, front/src/components/PrioritySelector.jsx, front/src/styles/PriorityIcon.module.css, front/src/styles/PrioritySelector.module.css
- PriorityIcon 클래스 조건 수정
- BrightStarIcon 클래스 조건 수정
- PrioritySelector 추가
close #68
=> [Add] PrioritySelector 추가

back/.eslintrc, back/src/controllers/v1/account.controller.ts, back/src/models/user.model.ts, back/src/routes/v1/account.route.ts, back/src/services/v1/account.service.ts, back/src/services/v1/profile.service.ts
=>  [Chore] Boolean타입을 가진 변수명 flag => is로 변경 외 1

back/src/controllers/v1/task.controller.ts, back/src/models/task.model.ts, back/src/routes/v1/task.route.ts, back/src/services/v1/task.service.ts
=> [Add] Task 등록 API 생성 외 1

back/src/controllers/v1/task.controller.ts, back/src/models/user.model.ts, back/src/routes/v1/task.route.ts, back/src/services/v1/task.service.ts
=> [Add] task 삭제 API 외 1

front/src/styles/Button.module.css
퀵버튼 css 스타일링했습니다.
수정사항 있으면 말씀해주세요 😊
close #96
=> [Add] 퀵버튼 css 스타일링

README.md
=> [Add]README.md 시안

back/src/controllers/v1/tag.controller.ts, back/src/controllers/v1/task.controller.ts, back/src/models/user.model.ts, back/src/routes/v1/task.route.ts, back/src/services/v1/tag.service.ts, back/src/services/v1/task.service.ts
=> [Add] task 수정 API 외 2

front/src/components/TaskItem.jsx, front/src/styles/Button.module.css, front/src/styles/CheckButton.module.css, front/src/styles/PriorityIcon.module.css, front/src/styles/Tag.module.css, front/src/styles/TaskItem.module.css, front/src/styles/common/color.css
투두리스트 스타일링입니다.
디자인을 늦게봐서 별이랑 체크박스랑 위치를 바꿔서 스타일링해버렸네요 ㅠㅠㅠ
나중에 :checked 기능 추가할 때 다시 건드려보도록 하겠습니다!
이리저리 위치를 바꾼다고 taskitem.jsx의  classname 명과 div설정을 엉망진창으로 ㅎㅎㅎ.....손을 댔는데 바꿔야한다면 말씀 꼭꼭 부탁드립니다! div도 제대로 한 것 맞는지 봐주시면 감사하겠습니다....!
close #112
=> [Add] 투두리스트 css 스타일링

back/apidoc.json, back/src/controllers/v1/tag.controller.ts, back/src/models/tag.model.ts, back/src/models/task.model.ts, back/src/routes/v1/account.route.ts, back/src/routes/v1/tag.route.ts, back/src/routes/v1/task.route.ts, back/src/services/v1/tag.service.ts
=> [Add] tag 생성 API 외 4

front/src/components/QuickAddForm.jsx, front/src/components/TaskItem.jsx, front/src/container/Navbar.jsx, front/src/container/TaskModal.jsx, front/src/page/Main.jsx, front/src/reducer/modal.js, front/src/reducer/tasks.js, front/src/store/store.js
close #122  [Add] 모달 토글
close #121 [Add] Task 삭제
=> [Add] Feat/youngrongoh #121 #122

back/apidoc.json, back/src/controllers/v1/tag.controller.ts, back/src/routes/v1/tag.route.ts, back/src/routes/v1/task.route.ts, back/src/services/v1/tag.service.ts
close #116 tag 조회 API
close #115 tag 수정 API
close #117 tag 삭제 API
=> feat/castleMo #116 #115 #117

back/apidoc.json, back/src/controllers/v1/account.controller.ts, back/src/controllers/v1/profile.controller.ts, back/src/models/user.model.ts, back/src/routes/v1/account.route.ts, back/src/routes/v1/profile.route.ts, back/src/services/v1/account.service.ts, back/src/services/v1/profile.service.ts, back/src/services/v1/tag.service.ts, back/src/services/v1/task.service.ts
close #133  user model 수정
close #135 Tutorial 완료 API
close #132 profile 조회 API
=> Feat/castleMo #113 #135 #132

front/package.json, front/src/components/GoogleLoginButton.jsx, front/src/components/GoogleLogoutButton.jsx, front/src/components/ProfileImage.jsx, front/src/components/ProfileModal.jsx, front/src/container/Navbar.jsx, front/src/page/Login.jsx, front/src/page/Tutorial.jsx, front/src/reducer/profile.js, front/src/styles/Button.module.css, front/src/styles/Input.module.css, front/src/utils/account-manager.js
=> [Add] 로그인 프로세스 #136

front/src/components/Input.jsx, front/src/components/ProfileModal.jsx, front/src/components/QuickAddForm.jsx, front/src/components/TaskForm.jsx, front/src/page/Main.jsx, front/src/reducer/profile.js, front/src/reducer/tasks.js, front/src/store/store.js
close #138  유효한 profile 데이터가 전달되지 않았을 때 표시될 기본값 설정
close #140 [Add] 빠른 태스크 추가 기능
close #142 [Add] TaskModal에서 태스크 등록 기능
=> [Add] feat/youngrongoh #138 #140 #142

front/src/components/TaskForm.jsx, front/src/styles/Button.module.css, front/src/styles/Input.module.css, front/src/styles/InputBox.module.css, front/src/styles/Modal.module.css, front/src/styles/PeriodsInputBox.module.css, front/src/styles/PriorityIcon.module.css, front/src/styles/PrioritySelector.module.css, front/src/styles/TaskForm.module.css, front/src/styles/common/color.css
https://user-images.githubusercontent.com/80464961/117016223-73a10c80-ad2d-11eb-8d4d-f69436d9c21d.mov
https://user-images.githubusercontent.com/80464961/117016366-9af7d980-ad2d-11eb-9e39-cb138099d60d.mov
태그 눌러보다가 발견했는데 띄어쓰기 할 때마다 태그박스 크기도 같이 커지고 
마지막에는 모달창 밖으로 튀어나가더라구요!
물론 저렇게 길게 태그를 입력할 사람은 없겠지만 혹시나 싶어 올려봅니다....!!
수정사항 있으면 말씀해주세요! 대환영입니다 😁
close #125
=> [Add] task modal css style

back/src/controllers/v1/profile.controller.ts, back/src/routes/v1/profile.route.ts, back/src/services/v1/profile.service.ts
=> feat/castleMo #131

back/src/controllers/v1/task.controller.ts, back/src/models/task.model.ts, back/src/routes/v1/tag.route.ts, back/src/routes/v1/task.route.ts, back/src/services/v1/task.service.ts
close #146 task 생성 및 수정 API에 mainTag 추가
close #99 task 조회 API
=> Feat/castleMo #146 #99

front/src/components/Calendar.jsx, front/src/styles/Button.module.css, front/src/styles/Calendar.css, front/src/styles/Calendar.module.css
https://user-images.githubusercontent.com/80464961/117248224-91c85300-ae7a-11eb-86e0-0c9afd97c6ee.mov
캘린더 스타일링입니다. 
전체 화면 비율 변경 후 사이즈 다시 조절할 예정입니다.
(arrow button 간격이 안 맞아보이는데 이미지 변경 후 조절하도록 하겠습니다!)
캘린더에 수정해야 할 사항이 있습니다.
캘린더.jsx 파일과 캘린더.css 파일 연결 부탁드립니다.어캐하는지 몰라서 야매(?)로 연결 해놨거든용.... 부탁드립니다!
(근데 캘린더.css파일 common 파일들 (color, size 등...)이랑 연결이 왜 안 되는 걸까요??🥲 @value로 연결했는데도 아무 변화가 없네요 ㅠㅠㅠ)
그리고 arrowbutton의 방향이 반대입니다. 두 arrowbutton의 버튼 이미지만 바꾸면 될 것 같아요!
두가지 더 추가하고 싶은게 있는데 그건 나중에 다시 말씀드리겠습니다! (급한 건 아니라...)
그럼 캘린더 css에서 수정하고 싶은 사항 있으면 꼭 꼭 말씀부탁드립니다~~!
--------------------------------
수정 완료!
close #145
=> [Add] 캘린더 스타일링

front/src/components/Calendar.jsx, front/src/components/DateInputBox.jsx, front/src/components/DivisionInput.jsx, front/src/components/GoogleLoginButton.jsx, front/src/components/GoogleLogoutButton.jsx, front/src/components/Input.jsx, front/src/components/InputBox.jsx, front/src/components/NumberInput.jsx, front/src/components/PeriodInputBox.jsx, front/src/components/PrioritySelector.jsx, front/src/components/ProfileModal.jsx, front/src/components/TagButton.jsx, front/src/components/TagInputBox.jsx, front/src/components/TaskForm.jsx, front/src/page/Main.jsx, front/src/page/Tutorial.jsx, front/src/reducer/tasks.js, front/src/styles/page/Login.module.css, front/src/utils/color-manager.js, front/src/utils/id-generator.js, front/src/utils/timestamp-parser.js
close #150 [Add] PeriodInputBox 커스터마이징
close #151 [Add] 가입 시 기본 프로필 이미지 변경
close #152 [Add] 태스크 등록 시 태그 정보 함께 추가
close #153 [Add] id generator 코드 분리
close #154 [Add] TaskModal에서 태그 삭제 기능 추가
close #155 [Fix] 콘솔 경고 메시지 정리
=> Feat/youngrongoh #150 #151 #152 #153 #154 #155

.gitattributes
- 커밋할 때 lf로 개행문자 처리
- 체크아웃 할 때 OS에 따라 개행문자 처리
자세한 사항은 [노션 스터디노트](https://www.notion.so/CRLF-LF-d2331de8250c49fe9fffd9165fc4f259) 참고
close #159
=> [Chore] git 개행문자 설정 #159

front/src/page/Tutorial.jsx
인풋 수정으로 인해 props명 변경
close #163
=> [Fix] 튜토리얼에서 데이터 받아오지 못하는 문제 수정 #163

front/.eslintrc.json, front/.storybook/main.js, front/.storybook/preview.js, front/package.json, front/src/App.jsx, front/src/stories/atoms/Button.stories.js, front/src/styles/App.css, front/src/styles/index.css, front/yarn.lock
지난 주 회의 때 새로 도입하기로 했던 스토리북을 추가했습니다.
본 PR이 머지된 이후에 `front` 폴더에서 `yarn install`을 실행해주세요🤗
패키지 최신화를 하신 다음,
`front` 폴더에서 `yarn storybook`을 실행하면 스토리북을 사용할 수 있습니다🙌
현재는 기본 버튼 컴포넌트만 있으나
이틀 내로 지금까지 만들어진 컴포넌트를 모두 추가할 예정이며,
이후 추가되는 컴포넌트도 바로바로 스토리를 작성하도록 하겠습니다!
궁금한 사항 있으시면 언제든 게더타운으로 오세요~😎
close #168
=> [Chore] Storybook 추가 #168 

front/src/components/InputBox.jsx, front/src/components/ProfileModal.jsx, front/src/container/TasksContainer.jsx, front/src/page/Login.jsx, front/src/page/Main.jsx, front/src/reducer/profile.js, front/src/reducer/tasks.js, front/src/reducer/token.js, front/src/store/store.js, front/src/utils/account-manager.js
close #177 [Add] 프로필 수정
close #180 [Add] 서버로부터 테스크 조회하여 업데이트
=> [Add] 프로필 수정 #177 #180

front/src/stories/pages/Login.stories.jsx, front/src/stories/pages/Main.stories.jsx, front/src/stories/pages/Tutorial.stories.jsx
- front/src/pages에 위치한 컴포넌트 스토리 추가
=> [Feat] pages 스토리 추가

front/src/components/InputBox.jsx, front/src/components/ProfileModal.jsx, front/src/styles/Button.module.css, front/src/styles/Input.module.css, front/src/styles/InputBox.module.css
=> Feat/hyunbins  #208 

front/src/components/PeriodInputBox.jsx, front/src/styles/Button.module.css, front/src/styles/DateInputBox.module.css, front/src/styles/Input.module.css, front/src/styles/InputBox.module.css, front/src/styles/PeriodsInputBox.module.css, front/src/styles/PrioritySelector.module.css, front/src/styles/QuickAddForm.module.css, front/src/styles/TaskForm.module.css, front/src/styles/page/Login.module.css
https://user-images.githubusercontent.com/80464961/118225056-4daf0100-b4bf-11eb-9078-4566651642cd.mov
로그인 튜토리얼 창의 세부적인 사항들을 수정하였습니다.
요소간의 간격을 조정했습니다.
https://user-images.githubusercontent.com/80464961/118229827-a5516a80-b4c7-11eb-9299-74eeae87affa.mov
투두 등록폼의 디자인을 수정하였습니다.
입력 폼의 색을 바꿔 피그마 디자인과 유사하게 적용하였습니다.
태스크 폼의 디자인을 수정하였습니다.
전체 디자인과 통일성이 어긋나있는 효과들, 글자 들 사이의 간격, 글씨 크기를 조정했습니다.
close #202 
close #203
=> [Add] 로그인 튜토리얼 창 세부 수정

front/src/styles/Input.module.css
=> [Feat] 인풋 중괄호 수정

front/src/styles/InputBox.module.css
=> [feat] 테스크 모달 글자 스타일 수정 #213

front/src/components/CategoryDivider.jsx, front/src/components/QuickAddForm.jsx, front/src/components/TaskForm.jsx, front/src/components/TaskList.jsx, front/src/container/TasksContainer.jsx, front/src/reducer/tasks.js, front/src/styles/CategoryDivider.module.css, front/src/styles/page/Main.module.css, front/src/utils/account-manager.js, front/src/utils/timestamp-parser.js
close #231 [Feat] 태스크 체크 상태 바인딩
close #230 [Feat] 태스크 리스트 날짜별 스크롤 기능 추가
=> 체크상태 바인딩, 리스트 날짜별 분류, 스크롤 #231 #230

front/src/components/Calendar.jsx, front/src/components/CategoryDivider.jsx, front/src/components/useCalendar.jsx, front/src/container/TasksContainer.jsx
- useCalendar 날짜 포멧팅 변경
- Calendar 날짜 클릭 이벤트 추가
- CategoryDivider data 속성 추가
- TasksContainer에서 CategoryDivider로 date 값 주입
close #234
=> [Feat] 캘린더 날짜 클릭하면 태스크 리스트 스크롤 하는 기능 #234

front/src/styles/Calendar.module.css, front/src/styles/Input.module.css, front/src/styles/TaskForm.module.css, front/src/styles/ToggleSwitch.module.css, front/src/styles/page/Main.module.css
1. 캘린더 월 잘림 현상을 수정했습니다.
2. 태스크 폼의 오류 수정을 했습니다.
3. 설정창 스타일링을 하였습니다. 주말이 끝난 후 다시 수정할 예정입니다.
https://user-images.githubusercontent.com/80464961/119215913-98f29080-bb0b-11eb-83ce-26d896b4d8a4.mov
close #229
=> [Feat] 태스크폼, 캘린더 월, 설정 창 스타일링 및 오류수정

front/src/components/DailyNavbar.jsx, front/src/components/TaskItem.jsx, front/src/container/DailyContainer.jsx, front/src/container/Layout.jsx, front/src/container/Navbar.jsx, front/src/page/Main.jsx, front/src/stories/components/DailyNavbar.stories.jsx, front/src/stories/components/TaskItem.stories.jsx, front/src/stories/containers/DailyContainer.stories.jsx, front/src/styles/Button.module.css, front/src/styles/DailyContainer.module.css, front/src/styles/DailyNavbar.module.css, front/src/styles/Layout.module.css, front/src/styles/TaskItem.module.css, front/src/utils/timestamp-parser.js
데일리 페이지를 추가했습니다.
네브바에서 메뉴 선택하여 이동 할 수 있습니다.
close #247
=> [Feat] 데일리 페이지 추가 #247

front/src/components/ProfileModal.jsx, front/src/styles/Button.module.css, front/src/styles/ProfileModal.module.css
Reverts LM-channel-team-project/WantoDo#245
오류가 있어 revert 요청합니다
=> Revert "Feat/front 프로필 모달 창 수정 방법 변경"

front/src/components/ProfileModal.jsx, front/src/page/Main.jsx, front/src/styles/Button.module.css, front/src/styles/ProfileModal.module.css
=> [fix] 프로필 모달 오류 수정

front/src/components/DailyNavbar.jsx, front/src/components/QuickButton.jsx, front/src/container/DailyContainer.jsx, front/src/container/QuickModal.jsx, front/src/page/Main.jsx, front/src/reducer/modal.js, front/src/styles/Button.module.css, front/src/styles/DailyContainer.module.css, front/src/styles/Modal.module.css, front/src/styles/Tag.module.css, front/src/utils/color-manager.js
태그 pink 색상 적용
DailyNavbar에서 선택된 날짜에 today 클래스를 추가했습니다.
데일리에 QuickButton 추가
close #263 
close #264 
close #266
=> [Feat] #263 #264 #266

front/src/components/ModalHeader.jsx, front/src/components/QuickAddForm.jsx, front/src/components/TaskForm.jsx, front/src/container/AlertModal.jsx, front/src/container/Modal.jsx, front/src/container/QuickModal.jsx, front/src/container/SettingContainer.jsx, front/src/container/TaskModal.jsx, front/src/container/TasksContainer.jsx, front/src/container/WithdrawalModal.jsx, front/src/page/Main.jsx, front/src/reducer/modal.js, front/src/stories/components/ModalHeader.stories.jsx, front/src/stories/containers/AlertModal.stories.jsx, front/src/stories/containers/QuickModal.stories.jsx, front/src/stories/pages/Main.stories.jsx, front/src/styles/AlertModal.module.css, front/src/styles/Modal.module.css, front/src/styles/ModalHeader.module.css, front/src/styles/WithdrawalModal.module.css
경고창을 추가했습니다.
- 다른 모달과 다르게 사용자가 닫기, 취소, 확인 버튼을 클릭해야만 닫히도록 구현했습니다.
(경고창 외부를 클릭해도 닫히지 않습니다)
- 취소 버튼과 확인 버튼 각각 클래스 부여 했습니다.
close #268
=> [Feat] 커스텀 경고창 추가

front/src/styles/Button.module.css
데일리 투데이의 color 수정을 하였습니다. (피그마 디자인과 같게)
close #270
=> [Feat] 데일리 투데이 css 스타일링

front/src/components/Calendar.jsx, front/src/components/DateInputBox.jsx, front/src/components/DivisionInput.jsx, front/src/components/NumberInput.jsx, front/src/components/PeriodInputBox.jsx, front/src/components/TaskForm.jsx, front/src/components/useCalendar.jsx, front/src/container/CalendarInputModal.jsx, front/src/stories/containers/CalenderInputModal.stories.jsx, front/src/styles/Button.module.css, front/src/styles/Calendar.module.css, front/src/styles/CalendarInputModal.module.css, front/src/styles/DateInputBox.module.css, front/src/styles/Modal.module.css, front/src/utils/timestamp-parser.js
날짜 선택창을 추가했습니다.
- 태스크 폼에서 캘린더 버튼을 클릭하면 날짜 선택창이 표시됩니다.
- 모달 내에서 날짜 선택창 바깥을 클릭하면 날짜 선택창이 닫힙니다.
날짜 데이터를 처리하는 방식을 변경했습니다.
- 태스크 폼에서는 별도의 데이터 변환 없이 상태관리 및 서버 통신을 할 수 있도록 타임스탬프로 관리합니다.
- 폼 하위에 있는 DateInputBox에서는 각 인풋으로 데이터를 전달하기 위해 객체로 변환합니다.
close #276
=> [Feat] 커스텀 날짜 선택창 추가

front/src/components/DateInputBox.jsx, front/src/components/PeriodInputBox.jsx, front/src/components/PrioritySelector.jsx, front/src/components/QuickAddForm.jsx, front/src/components/Tag.jsx, front/src/components/TagButton.jsx, front/src/components/TagInputBox.jsx, front/src/components/TaskForm.jsx, front/src/container/AutoCompleteBox.jsx, front/src/container/QuickAddLayout.jsx, front/src/container/SettingContainer.jsx, front/src/container/TagModal.jsx, front/src/container/TaskModal.jsx, front/src/container/TasksContainer.jsx, front/src/page/Main.jsx, front/src/styles/AutoCompleteBox.module.css, front/src/styles/Button.module.css, front/src/styles/DateInputBox.module.css, front/src/styles/Input.module.css, front/src/styles/InputBox.module.css, front/src/styles/Modal.module.css, front/src/styles/TagButton.module.css, front/src/styles/TagModal.module.css, front/src/utils/account-manager.js, front/src/utils/timestamp-parser.js
기간에 대한 유효성 검사를 추가 했습니다.
- PeriodInputBox 유효성 검사 추가
- 초단위까지 비교
- 시작일이 종료일보다 늦거나, 종료일이 시작일보다 빠르면 경고창 표시
태스크 모달을 닫을 때 변경 사항이 있으면 확인창을 표시하는 기능을 추가했습니다.
- 제목이나 중요도, 기간, 태그 중 하나라도 변경 사항이 생기면 닫기 전에 확인창 표시
- 변경 사항을 지우고 닫을 때는 확인창 표시하지 않음
태그 자동완성 기능을 추가했습니다.
- 태스크 모달에서 태그 이름 입력 시 이미 등록된 태그를 조회하여 비슷한 태그를 추천
- 자동완성 리스트에 있는 태그 클릭하면 태그 추가
- 중복된 이름으로 태그 추가 안됨
- 태그 모달에서도 자동완성 동작
- 태그 모달에서 자동완성에 있는 태그 클릭하거나 이미 등록된 태그 등록하면 
해당 태그로 스크롤하면서 반짝이는 애니메이션 표시
메인태그를 변경 할 때 애니메이션을 추가했습니다.
- 마우스 왼쪽 버튼 누르고 있으면 애니메이션 실행
close #279 
close #281 
close #282 
close #283
=> [Feat] #279 #281 #282 #283

back/src/services/v1/account.service.ts, back/src/services/v1/tag.service.ts, back/src/services/v1/task.service.ts
- deleteTag API task의 tag 삭제 기능 추가
close #274
=> [Feat] deleteTag API task의 tag 삭제 기능 추가

.gitignore, front/package.json, front/public/_redirects, front/src/App.jsx, front/yarn.lock
=> [Chore] 배포 관련 세팅 #286
